#!/bin/sh

help() {
	echo "\
Usage: $0 {1, 2, ..., 5}...
Make NAV collect \$1 assigned addresses at t, \$2 assigned addresses at t+5min, ..., \$N+1 assigned addresses at t+5Nmin
" >&2
}

acquire() {
	sudo docker compose exec kea clear-leases || exit 1
	for i in $(seq 1 "$1"); do
		sudo docker compose exec "client$i" dhcpcd-run || exit 1
	done
}

collect() {
	sudo docker compose exec nav dhcpmetrics --timeoffset="$1" || exit 1
}

timed() {
	out="$(LC_NUMERIC="en_US.UTF-8" time -p "$@" 2>&1 >/dev/null)"
	echo "$out" | head -n1 | cut -d" " -f2 | cut -d"." -f1
}

for i in $(seq 1 "$#"); do
	if ! { test "$1" -ge 1 && test "$1" -le 5; } 2>/dev/null; then
		help
	fi
done

timeoffset=0
while test "$#" -gt 0; do
	timespent1=$(timed acquire "$1")
	timespent2=$(timed collect "$timeoffset")
	timeoffset=$((timeoffset + 300 - timespent1 - timespent2))
	shift 1
done
