services:
  client1:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      kea:
        ipv4_address: 172.31.255.129

  client2:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      kea:
        ipv4_address: 172.31.255.130

  client3:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      kea:
        ipv4_address: 172.31.255.131

  client4:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      kea:
        ipv4_address: 172.31.255.132

  client5:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      kea:
        ipv4_address: 172.31.255.133

  kea:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.kea
    networks:
      kea:
        ipv4_address: 172.31.255.134
      nav:

networks:
  kea:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.255.0/24
          ip_range: 172.31.255.128/25
  nav:
    external: true
    name: "${NAV_NETWORK:-nav_default}"
