#!/bin/sh

# We need kea-dhcp4 to only serve the kea network (not the nav network). So we need to configure
# it to only use the kea link interface.
# Docker doesn't seem to have a way of a-priori knowing the name of link interfaces that the runtime
# creates, so we must find out after link interfaces have been created, and then afterwards we can
# create the kea-dhcp4 config file.
iface="$(ip -o -4 route show to "172.31.255.0/24" | cut -d' ' -f3 -)"

mkdir -p /etc/kea
cat <<EOF > /etc/kea/kea-dhcp4.conf
{
    "Dhcp4": {
        "subnet4": [
            {
                "subnet":  "172.31.255.0/24",
                "pools": [
                    {
                        "pool": "172.31.255.0/25"
                    }
                ],
                "id": 1,
                "interface": "$iface"
            }
        ],
        "interfaces-config": {
            "interfaces": [
                "$iface"
            ],
            "service-sockets-max-retries": 5,
            "service-sockets-require-all": true
        },
        "control-socket": {
            "socket-type": "unix",
            "socket-name": "/run/kea/control_socket_4"
        },
        "renew-timer": 1000,
        "rebind-timer": 2000,
        "valid-lifetime": 4000,
        "loggers": [
            {
                "name": "kea-dhcp4",
                "output_options": [
                    {
                        "output": "stdout"
                    }
                ],
                "severity": "INFO"
            }
        ],
        "lease-database": {
            "type": "memfile",
            "name": "/var/lib/kea/kea-leases4.csv"
        }
    }
}
EOF

exec /usr/sbin/kea-dhcp4 -c /etc/kea/kea-dhcp4.conf
