#!/bin/sh

# We need kea-dhcp4 to only serve the kea network (not the nav network). So we need to configure
# it to only use the kea link interface.
# Docker doesn't seem to have a way of a-priori knowing the name of link interfaces that the runtime
# creates, so we must find out after link interfaces have been created, and then afterwards we can
# create the kea-dhcp4 config file.
iface="$(ip -o -4 route show to "172.31.255.0/24" | cut -d' ' -f3 -)"

mkdir -p /etc/kea
cat <<EOF > /etc/kea/kea-dhcp4.conf
{
    "Dhcp4": {
"subnet4": [
                {
                    "id": 1,
                    "subnet": "192.0.1.0/24",
                    "pools": [{"pool": "192.0.1.1-192.0.1.10", "pool-id": 1}]
                },
                {
                    "id": 2,
                    "subnet": "192.0.2.0/24",
                    "pools": [
                        {"pool": "192.0.2.1-192.0.2.10", "pool-id": 1},
                        {"pool": "192.0.2.128/25", "pool-id": 2},
                        {"pool": "192.0.2.32/28", "pool-id": 3}
                    ]
                }
            ],
            "shared-networks": [
                {
                    "name": "shared-network-1",
                    "subnet4": [
                        {
                            "id": 3,
                            "subnet": "192.0.3.0/24",
                            "pools": [
                                {"pool": "192.0.3.1-192.0.3.10", "pool-id": 1}
                            ]
                        },
                        {
                            "id": 4,
                            "subnet": "192.0.4.1/24",
                            "pools": [
                                {"pool": "192.0.4.1-192.0.4.5", "pool-id": 1}
                            ]
                        }
                    ],
                },
                {
                    "name": "shared-network-2",
                    "subnet4": [
                        {
                            "id": 5,
                            "subnet": "192.0.5.0/24",
                            "pools": [
                                {"pool": "192.0.5.1-192.0.5.5", "pool-id": 1}
                            ]
                        }
                    ]
                }
            ],
        "interfaces-config": {
            "interfaces": [
                "$iface"
            ],
            "service-sockets-max-retries": 5,
            "service-sockets-require-all": true
        },
        "control-socket": {
            "socket-type": "unix",
            "socket-name": "/run/kea/control_socket_4"
        },
        "renew-timer": 1000,
        "rebind-timer": 2000,
        "valid-lifetime": 4000,
        "loggers": [
            {
                "name": "kea-dhcp4",
                "output_options": [
                    {
                        "output": "stdout"
                    }
                ],
                "severity": "INFO"
            }
        ],
        "lease-database": {
            "type": "memfile",
            "name": "/var/lib/kea/kea-leases4.csv"
        }
    }
}
EOF

exec /usr/sbin/kea-dhcp4 -c /etc/kea/kea-dhcp4.conf
